### ISSUE TITLE
print function

### ISSUE THREAD

**Issue by alessandro-canevaro** [Alessandro212977/BoardGame#2]
implement a function that prints the board on the terminal

**Comment by alessandro-canevaro** [comment]
Would be nice to have something like this: [https://stackoverflow.com/questions/69284125/printing-2048-board-in-python-with-spacing-with-standard-libraries](https://stackoverflow.com/questions/69284125/printing-2048-board-in-python-with-spacing-with-standard-libraries)
Do you think it is also possible to colour the tiles?

**Comment by HUIYULEO** [comment]
I would like to use the pygame to print board in this weekend
